@startuml
actor       User                        as user
entity      HomeComponent               as homeComponent
entity      ShoppingCartComponent       as ShoppingCart
entity      ShoppingCartIconComponent   as ShoppingCartIcon
database    ReduxStore                  as database
database    CounterSliceWithAction      as counterSliceWithAction

group send data and update the state process
    user                        -> homeComponent            : User click on **+1 button**
    homeComponent               -> database                 : Sends **action and reducer** by **useDispatch**
    note right
        Action: {
            type: 'incrementWithAction',
            payload: 10
        }
    end note
    database                    -> counterSliceWithAction   : Sends actions and reducer to counterSlice
    counterSliceWithAction      -> counterSliceWithAction   : State = State + Action.Payload
end

group subscribe process
    counterSliceWithAction      -> ShoppingCartIcon         : Push newState to subscriber component
    counterSliceWithAction      -> ShoppingCart             : Push newState to subscriber component
end
@enduml
